### ISSUE TITLE
vROps 7.5 articles

### ISSUE THREAD

**Issue by vineethac** [bethsouza/vROps#1]
I am currently working on vROps 7.5 blog series. Published 6 parts so far. More work in progress!
[Part1 - Installation](http://itimssupport.blogspot.com/2019/06/vrealize-operations-manager-75-part1.html)
[Part2 - Configure vCenter adapter and dashboards overview](http://itimssupport.blogspot.com/2019/06/vrealize-operations-manager-75-part2.html)
[Part3 - Rightsizing](http://itimssupport.blogspot.com/2019/07/vrealize-operations-manager-75-part3.html)
[Part4 - High availability](http://itimssupport.blogspot.com/2019/07/vrealize-operations-manager-75-part4.html)
[Part5 - Alerting](http://itimssupport.blogspot.com/2019/07/vrealize-operations-manager-75-part5.html)
[Part6 - Adding new symptoms and alert definitions](http://itimssupport.blogspot.com/2019/07/vrealize-operations-manager-75-part6.html)

Thanks
Vineeth

**Comment by bethsouza** [comment]
Hi Vineeth,
Thank you very much for contribute. And good work!
I'll include this!
