### ISSUE TITLE
Twitter additions and VMworld sessions

### ISSUE THREAD

**Issue by vmspot** [bethsouza/vROps#4]
Hi Beth,
Can you add @davidoverbeek and @ImNotoriousBDG to the twitter handles? That will cover all of the vRealize Operations technical marketing team including John and myself. "HCI1339BU	vSAN Administration Optimized Through vRealize Operations and Log Insight" would be a good addition to the list of VMworld sessions. And lastly, I haven't posted to my blog lately but it does include some good vROps resources http://www.vmspot.com/.

Thanks again for putting this together! This is AWESOME!!

**Comment by bethsouza** [comment]
Hi Matt,

Yes. Thank you!
I am glad to hear this! Always make happen things to contribute for community.
