### ISSUE TITLE
Update vRealize.vmware.com URL

### ISSUE THREAD

**Issue by vmspot** [bethsouza/vROps#6]
Hi Beth,

We've recently updated our vrealize.vmware.com site and have a new URL to use on your page. There is a re-direct from the old URL, but I was wondering if you wouldn't mind updating the product walkthrough URL to the following. 

https://vrealize.vmware.com/t/vrealize-operations/vrealize-operations-features-and-capabilities/

We also added this repo to our additional learning page. Thanks again for keeping this going!
https://vrealize.vmware.com/t/vrealize-operations/additional-learning-1/

**Comment by bethsouza** [comment]
Hi Matt,

Thanks to send the information. 
It is a pleasure for me to keep this work for the community.
